FROM node:22-bookworm-slim as build

RUN apt update
RUN apt install -y python3 make g++

WORKDIR /usr/local/app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install --legacy-peer-deps

COPY ./src /usr/local/app/src
COPY ./angular.json /usr/local/app/angular.json
COPY ./tsconfig.json /usr/local/app/tsconfig.json
COPY ./tsconfig.app.json /usr/local/app/tsconfig.app.json
COPY ./api/src/models /usr/local/app/api/src/models

# Accept build arg for Angular base-href
ARG BASE_HREF=/
ENV BASE_HREF=$BASE_HREF

# Pass base-href to Angular CLI
RUN npm run build -- --base-href $BASE_HREF

COPY ./nginx.conf /usr/local/app/nginx.conf

FROM nginx:latest as lnvisualizercontainer

COPY --from=build /usr/local/app/nginx.conf /nginx.conf.template
COPY --from=build /usr/local/app/dist/ln-visualizer /usr/share/nginx/html

EXPOSE 80

CMD ["/bin/sh" , "-c" , "envsubst '$LN_VISUALIZER_API_URL' < /nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]
